name: CI
on: push
jobs:
  build:
    name: Build & test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x, '*']

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm install --no-package-lock
      - run: npm test
      - run: npm run build-storybook --quiet

      - uses: actions/upload-artifact@v2
        # Only publish examples using the master branch, and only from one build
        if: github.ref == 'refs/heads/master' && matrix.node-version == '16.x'
        with:
          name: examples
          path: examples/*
          if-no-files-found: error

  publish:
    if: github.ref == 'refs/heads/master'
    name: Deploy storybook examples
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: examples
          path: examples

      - name: Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: examples
