name: CI
on:
  - push
  - pull_request
jobs:
  build:
    name: Build & test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 24.x

      - run: npm install --no-package-lock
      - name: Install Playwright for testing
        run: npx playwright install --with-deps

      - run: npm test

      - run: npm run build-storybook --quiet

      - uses: actions/upload-artifact@v4
        if: github.ref == 'refs/heads/main'
        with:
          name: examples
          path: examples/*
          if-no-files-found: error

  publish:
    if: github.ref == 'refs/heads/main'
    name: Deploy storybook examples
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: examples
          path: examples

      - name: Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: examples
